# Generated by Django 5.2.13 on 2026-04-19 02:30

import apps.tenants.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('api_key', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('mp_access_token', apps.tenants.fields.EncryptedField(blank=True, null=True, verbose_name='Token Mercado Pago')),
                ('webhook_notificacion', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Webhook de notificación')),
                ('smtp_host', models.CharField(blank=True, max_length=200, null=True, verbose_name='Servidor SMTP')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='Puerto SMTP')),
                ('smtp_user', models.CharField(blank=True, max_length=200, null=True, verbose_name='Usuario SMTP')),
                ('smtp_pass', apps.tenants.fields.EncryptedField(blank=True, null=True, verbose_name='Contraseña SMTP')),
                ('smtp_from', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email remitente')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'ordering': ['-created_at'],
            },
        ),
    ]
