# Generated by Django 5.2.13 on 2026-04-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='color_primario',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Color primario (hex)'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='color_secundario',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color secundario (hex)'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='cuit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CUIT'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='direccion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL del logo'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='razon_social',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Razón social'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='sitio_web',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Sitio web'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
    ]
