# Generated by Django 5.2.13 on 2026-04-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_negocio_resend_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='texto_footer',
            field=models.CharField(blank=True, help_text='Texto personalizado en el footer de todos los emails. Ej: "Líder en logística del norte"', max_length=500, null=True, verbose_name='Texto del pie de email'),
        ),
    ]
