# Generated by Django 5.2.13 on 2026-04-19 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_id', models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('amount', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('in_process', 'En proceso')], default='pending', max_length=50)),
                ('init_point', models.TextField(blank=True, null=True)),
                ('metadata_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='tenants.negocio')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
