# Generated by Django 5.2.13 on 2026-04-19 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador único. Ej: recupero-clave, pago-confirmado', max_length=100)),
                ('asunto', models.CharField(help_text='Soporte de variables Jinja2: {{ nombre }}, {{ link }}', max_length=500)),
                ('cuerpo_html', models.TextField(help_text='HTML completo del email. Soporta variables Jinja2: {{ variable }}')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='tenants.negocio')),
            ],
            options={
                'verbose_name': 'Plantilla de Email',
                'verbose_name_plural': 'Plantillas de Email',
                'ordering': ['negocio', 'slug'],
                'unique_together': {('negocio', 'slug')},
            },
        ),
    ]
